# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://traindb-project.github.io
title: TrainDB
email: taewhi@etri.re.kr
author: Taewhi Lee
description: > # "Write an awesome description for your new site here. 
  TrainDB is a ML-based approximate query processing engine that aims to answer time-consuming analytical queries in a few seconds.
copyright: 'Copyright &copy; 2021-2024 TrainDB project. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/traindb-project/traindb
  - title: documentation (kor)
    url: https://traindb-project.github.io/traindb-doc/ko
